### ISSUE TITLE
db_name parameter in connection not effective

### ISSUE THREAD

**Issue by instantkaffee** [Appsilon/shiny.collections#20]
Seems the db_name parameter is hard-coded and fixed to "shiny".

Propose to modify code and make db_name in yaml available.

**Comment by dokato** [comment]
Default database name `DEFAULT_DB ` is indeed hard-coded, but in general `db_name` is a parameter of connection. Look at: https://github.com/Appsilon/shiny.collections/blob/master/R/connection.R#L58.

**Comment by instantkaffee** [comment]
This is correct, nevertheless when inserting the hardcoded database is used.

```
insert <- function(collection, element, ...) {
  rethinker::r()$db(DEFAULT_DB)$table(collection$name)$insert(
    element, ...
  )$run(collection$connection$raw_connection)
}

```

**Comment by dokato** [comment]
True. Definitely to be fixed ASAP. Thanks for pointing this out!

**Comment by instantkaffee** [comment]
Thx
