### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by happyshows** [Appsilon/shiny.collections#6]
```
> connection <- shiny.collections::connect()
Error in socketConnection(host, port, open = "w+b", blocking = TRUE) : 
  cannot open the connection
In addition: Warning message:
In socketConnection(host, port, open = "w+b", blocking = TRUE) :
  localhost:28015 cannot be opened
```

**Comment by dokato** [comment]
@happyshows You must ensure that `rethinkdb` is running. Check out https://www.rethinkdb.com/ for installation and setting up hints.

(issue related to #3 )

**Comment by happyshows** [comment]
@dokato  thanks. I just saw the news that rethinkdb is closing down, will you continue to work on this package?

**Comment by dokato** [comment]
@happyshows AFAIK only a company behind rethinkdb is closing down, but it still has very active open source community (take a look at: https://github.com/rethinkdb/rethinkdb), so we will continue to develop `shiny.collections`.

**Comment by happyshows** [comment]
Is there any live demo of shiny.collection package that I can access before I install the db?

**Comment by dokato** [comment]
Working on it ;) currently I'm developing a simple chat app, but it still requires some amendments to add - should be ready next week. If you want to take a look at a code, see PR #7 .
